apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: colin-gpt-bert-pvc
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi