apiVersion: v1
kind: Pod
metadata:
  name: pvc-debug
spec:
  restartPolicy: Never
  containers:
    - name: shell
      image: ubuntu:22.04
      command: ["bash", "-lc"]
      args: ["sleep 36000"]
      volumeMounts:
        - name: workspace
          mountPath: /workspace
  volumes:
    - name: workspace
      persistentVolumeClaim:
        claimName: dpo-sweep-storage