apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dpo-sweep-storage
  namespace: dsc-capstone-25-26
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-ceph-block